apiVersion: v1
kind: PersistentVolume
metadata:
  name: flowui-backend-volume-dev
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /flowui_dev/backend
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - flowui-cluster-worker
