# Default values for installing FlowUI in a K8s cluster

github_access_token: ~

# Frontend service
frontend:
  enabled: true
  image: taufferconsulting/flowui-frontend:latest
  # internalPort: 3000
  # entrypointCommand: ["/bin/bash"]
  # entrypointArgs: ["-c", "yarn start:local"] # Running it in local mode to communicate with local api

# Backend service
backend:
  enabled: true
  image: taufferconsulting/flowui-backend:latest
  # entrypointCommand: ["/bin/bash"]
  # entrypointArgs: ["-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]

# Databse service - do not use in production
database:
  image: postgres
  name: postgres
  user: postgres
  password: postgres

# Airflow services override
airflow:
  enabled: false
  images:
    useDefaultImageForMigration: true
    airflow:
      repository: taufferconsulting/flowui-airflow-base
      tag: 0.1.0
      pullPolicy: IfNotPresent
  dags:
    gitSync:
      enabled: true
      wait: 60 # interval between git sync attempts in seconds
      repo: ssh://git@github.com/Tauffer-Consulting/flowui_dev_workflows_repo.git
      branch: main
      subPath: "workflows"
      sshKeySecret: ~
