# Default values for installing FlowUI in a K8s cluster

github_access_token: ~

# Frontend service
frontend:
  enabled: true
  image: taufferconsulting/flowui-frontend:latest
  # internalPort: 3000
  # entrypointCommand: ["/bin/bash"]
  # entrypointArgs: ["-c", "yarn start:local"] # Running it in local mode to communicate with local api

# Backend service
backend:
  enabled: true
  image: taufferconsulting/flowui-backend:latest
  # entrypointCommand: ["/bin/bash"]
  # entrypointArgs: ["-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]

# Change this if using external Database
database:
  image: postgres
  name: postgres
  user: postgres
  password: postgres
# # Databse service - do not use in production
# database:
#   enabled: true
#   image: postgres
#   db_name: postgres
#   db_user: postgres
#   db_password: postgres

# # Airflow services override
# airflow:
#   enabled: true
#   images:
#     useDefaultImageForMigration: true
#     airflow:
#       repository: taufferconsulting/flowui-airflow-base
#       tag: 0.1.0
#       pullPolicy: IfNotPresent
#   extraSecrets:
#     airflow-ssh-secret:
#       data: |
#         gitSshKey: ~
